fixtures:
  symlinks:
    packages: "#{source_dir}"
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.1.0"
    boxen:
      repo: "git://github.com/boxen/puppet-boxen"
      ref: "3.4.2"
    repository:
      repo: "git://github.com/boxen/puppet-repository"
      ref: "2.2.0"
