#!/bin/sh

########################################################################
# Shell agnostic path setup
########################################################################

# Stephen's Scripts
export PATH=$PATH:.
export PATH=$PATH:~/bin
