# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="scopp"

# User specific variables
#export PS1='[\t] \[\033[01;31m\]\u@\h \[\033[01;32m\]\w\[\033[00m\] $ '
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk/Contents/Home
export ANT_HOME=/opt/ant
export ANT_OPTS='-Xmx1024m -XX:MaxPermSize=256m'
export JMETER_HOME=/opt/jmeter

export ANDROID_HOME=/usr/local/opt/android-sdk
export ANDROID_NDK_ROOT=/usr/local/opt/android-ndk

export PATH=$PATH:$HOME/bin:/sbin:/usr/sbin:$HOME/.jenv/bin:$ANT_HOME/bin:$JMETER_HOME/bin:$HOME/workspace/scripts

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git git-extras)

source $ZSH/oh-my-zsh.sh

eval "$(/opt/boxen/homebrew/bin/jenv init -)"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
# User specific aliases and functions
# Directory listings
# LS_COLORS='no=01;37:fi=01;37:di=07;96:ln=01;36:pi=01;32:so=01;35:do=01;35:bd=01;33:cd=01;33:ex=01;31:mi=00;05;37:or=00;05;37:'
# -G Add colors to ls
# -l Long format
# -h Short size suffixes (B, K, M, G, P)
# -p Postpend slash to folders
alias ll='ls -alhpG'
alias lt='ls -alhpt -G'
alias pp='ps -ef | grep -i'

alias rdesktop='/Applications/Remote\ Desktop\ Connection.app/Contents/MacOS/Remote\ Desktop\ Connection'
alias gitm='git fetch -p ; git merge origin/master ; git status -sb'
alias gitr='git fetch -p ; git rebase origin/master ; git status -sb'
alias gits='git status -sb'
alias gitcop='git checkout _parking_; git status -sb'

alias ci='ssh scopp@webcms-ci.webapps.rr.com'
alias ci00='ssh scopp@webcms-ci00.lab.webapps.rr.com'
alias ci-slave='ssh scopp@ci-slave01.lab.webapps.rr.com'
alias tower='ssh scopp@10.143.47.12'
alias alpha02='ssh scopp@webcms-alpha02.lab.webapps.rr.com'
alias beta01='ssh scopp@webcms-beta01.lab.webapps.rr.com'
alias beta02='ssh scopp@webcms-beta02.lab.webapps.rr.com'

#alias engr2aut1='ssh scopp@68.168.70.21'
#alias engr2aut2='ssh scopp@68.168.70.149'
#alias engr2pub1='ssh scopp@68.168.71.21'
#alias engr2pub2='ssh scopp@68.168.71.149'

alias engr2aut1='ssh scopp@webcms-auth01.engr2.webapps.rr.com'
alias engr2aut2='ssh scopp@webcms-auth02.engr2.webapps.rr.com'
alias engr2pub1='ssh scopp@webcms-pub01.engr2.webapps.rr.com'
alias engr2pub2='ssh scopp@webcms-pub02.engr2.webapps.rr.com'

alias engr1aut1='ssh scopp@webcms-auth01.engr1.webapps.rr.com'
alias engr1aut2='ssh scopp@webcms-auth02.engr1.webapps.rr.com'
alias engr1pub1='ssh scopp@webcms-pub01.engr1.webapps.rr.com'
alias engr1pub2='ssh scopp@webcms-pub02.engr1.webapps.rr.com'

alias engr2aut1host='webcms-auth01.engr2.webapps.rr.com'
alias engr2aut2host='webcms-auth02.engr2.webapps.rr.com'
alias engr2pub1host='webcms-pub01.engr2.webapps.rr.com'
alias engr2pub2host='webcms-pub02.engr2.webapps.rr.com'

alias paut1='ssh -l scopp webcms-auth01.cdp.webapps.rr.com'
alias paut2='ssh -l scopp webcms-auth02.cdp.webapps.rr.com'

alias ppub1='ssh -l scopp webcms-pub01.cdp.webapps.rr.com'
alias ppub2='ssh -l scopp webcms-pub02.cdp.webapps.rr.com'
alias ppub3='ssh -l scopp webcms-pub03.cdp.webapps.rr.com'
alias ppub4='ssh -l scopp webcms-pub04.cdp.webapps.rr.com'

alias pweb1='ssh -l scopp webcms-web01.cdp.webapps.rr.com'
alias pweb2='ssh -l scopp webcms-web02.cdp.webapps.rr.com'
alias pweb3='ssh -l scopp webcms-web03.cdp.webapps.rr.com'
alias pweb4='ssh -l scopp webcms-web04.cdp.webapps.rr.com'

[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh
