# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="scopp"

# User specific variables
#export PS1='[\t] \[\033[01;31m\]\u@\h \[\033[01;32m\]\w\[\033[00m\] $ '
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk/Contents/Home
export ANT_HOME=/opt/ant
export ANT_OPTS='-Xmx1024m -XX:MaxPermSize=256m'
export JMETER_HOME=/opt/jmeter

export SCAN_BUILD=/opt/scan-build
export ANDROID_HOME=/usr/local/opt/android-sdk
export ANDROID_NDK_ROOT=/usr/local/opt/android-ndk

export PATH=$PATH:$HOME/bin:/sbin:/usr/sbin:$HOME/.jenv/bin:$ANT_HOME/bin:$JMETER_HOME/bin:$HOME/workspace/scripts:$SCAN_BUILD:/opt/bin

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git git-extras)

source $ZSH/oh-my-zsh.sh

eval "$(/opt/boxen/homebrew/bin/jenv init -)"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
# User specific aliases and functions
# Directory listings
# LS_COLORS='no=01;37:fi=01;37:di=07;96:ln=01;36:pi=01;32:so=01;35:do=01;35:bd=01;33:cd=01;33:ex=01;31:mi=00;05;37:or=00;05;37:'
# -G Add colors to ls
# -l Long format
# -h Short size suffixes (B, K, M, G, P)
# -p Postpend slash to folders
alias ll='ls -alhpG'
alias lt='ls -alhpt -G'
alias pp='ps -ef | grep -i'

alias gitm='git fetch -p ; git merge origin/master ; git status -sb'
alias gitr='git fetch -p ; git rebase origin/master ; git status -sb'
alias gits='git status -sb'
alias gitd='git diff'
alias gitb='git branch'

alias buildsonar='ssh build@192.168.6.22'
alias build662='ssh build@192.168.7.148'
alias build667='ssh build@192.168.2.135'
alias build668='ssh build@192.168.5.249'
alias build669='ssh build@192.168.2.254'
alias build670='ssh build@192.168.3.252'
alias build1056='ssh build@192.168.6.66'
alias build1058='ssh build@192.168.6.54'
alias build1064='ssh build@192.168.6.76'
alias build1065='ssh build@192.168.6.77'
alias build1066='ssh build@192.168.6.75'
alias buildvm001='ssh build@192.168.6.26'

alias smoketest-od="/Applications/Unity/Unity.app/Contents/MacOS/Unity -batchmode -logfile -projectPath /Users/scopp/workspace/overdrive-one/unity/OverDrive -executeMethod Anki.TestScenario.RunTest"

alias build-setup='./tools/build-scripts/clean.sh ; ./configure.py ; ./tools/build-scripts/build_plugin.sh'
[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh

unalias git
